name: Test on push
on:
  push:
    branches:
      - main
      - 'v*'
  pull_request:
    branches:
      - main
      - 'v*'
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 22
      - run: npm ci
      - run: npm run test

